# Generated by Django 4.2.7 on 2025-10-21 20:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cardano', 'Cardano'), ('polkadot', 'Polkadot')], max_length=20, unique=True)),
                ('low_fee_rate', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('medium_fee_rate', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('high_fee_rate', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('mempool_size', models.BigIntegerField(default=0)),
                ('average_confirmation_time', models.IntegerField(default=0)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Fee Rate',
                'verbose_name_plural': 'Network Fee Rates',
                'db_table': 'network_fee_rate',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_address', models.CharField(max_length=255)),
                ('blockchain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cardano', 'Cardano'), ('polkadot', 'Polkadot')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36), django.core.validators.MinValueValidator(Decimal('1E-18'))])),
                ('fee', models.DecimalField(decimal_places=18, default=Decimal('0E-18'), max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('block_height', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('gas_limit', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('nonce', models.BigIntegerField(blank=True, null=True)),
                ('utxo_inputs', models.JSONField(blank=True, null=True)),
                ('change_address', models.CharField(blank=True, max_length=255, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='wallets.wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_by', models.CharField(max_length=255)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Lock',
                'verbose_name_plural': 'Transaction Locks',
                'db_table': 'transaction_lock',
                'indexes': [models.Index(fields=['expires_at'], name='transaction_expires_33090c_idx'), models.Index(fields=['locked_by'], name='transaction_locked__568a8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blockchain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cardano', 'Cardano'), ('polkadot', 'Polkadot')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('estimated_fee', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('fee_priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', max_length=10)),
                ('estimated_confirmation_time', models.IntegerField()),
                ('network_congestion', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('gas_limit', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=18, max_digits=36)])),
                ('sat_per_byte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Estimate',
                'verbose_name_plural': 'Transaction Estimates',
                'db_table': 'transaction_estimate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blockchain', 'created_at'], name='transaction_blockch_696de3_idx'), models.Index(fields=['user', 'created_at'], name='transaction_user_id_62567c_idx'), models.Index(fields=['correlation_id'], name='transaction_correla_b12eb2_idx'), models.Index(fields=['expires_at'], name='transaction_expires_d417f4_idx'), models.Index(fields=['is_used', 'created_at'], name='transaction_is_used_69bdde_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'Transaction Created'), ('validated', 'Transaction Validated'), ('signed', 'Transaction Signed'), ('broadcasted', 'Transaction Broadcasted'), ('confirmed', 'Transaction Confirmed'), ('failed', 'Transaction Failed'), ('cancelled', 'Transaction Cancelled'), ('retry', 'Transaction Retry'), ('status_updated', 'Status Updated')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('blockchain_response', models.JSONField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Audit Log',
                'verbose_name_plural': 'Transaction Audit Logs',
                'db_table': 'transaction_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction', 'created_at'], name='transaction_transac_0e3726_idx'), models.Index(fields=['correlation_id', 'created_at'], name='transaction_correla_87e965_idx'), models.Index(fields=['action', 'created_at'], name='transaction_action_a704fa_idx'), models.Index(fields=['user', 'created_at'], name='transaction_user_id_d87a11_idx'), models.Index(fields=['created_at'], name='transaction_created_8f8974_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status', 'created_at'], name='transaction_user_id_ad06fc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_wallet', 'status'], name='transaction_from_wa_1f1731_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['blockchain', 'status'], name='transaction_blockch_c3b457_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_hash'], name='transaction_transac_eec211_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['correlation_id'], name='transaction_correla_6f0ece_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_cb5aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['block_height'], name='transaction_block_h_2e3c09_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['confirmations'], name='transaction_confirm_a88c82_idx'),
        ),
    ]
