# Generated by Django 4.2.7 on 2026-09-02 17:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkfeerate",
            name="average_confirmation_time",
            field=models.IntegerField(
                default=0, verbose_name="average confirmation time (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="networkfeerate",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin"),
                    ("ethereum", "Ethereum"),
                    ("cardano", "Cardano"),
                    ("polkadot", "Polkadot"),
                ],
                max_length=20,
                unique=True,
                verbose_name="blockchain",
            ),
        ),
        migrations.AlterField(
            model_name="networkfeerate",
            name="congestion_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                verbose_name="congestion level",
            ),
        ),
        migrations.AlterField(
            model_name="networkfeerate",
            name="high_fee_rate",
            field=models.DecimalField(
                decimal_places=18,
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="high fee rate",
            ),
        ),
        migrations.AlterField(
            model_name="networkfeerate",
            name="low_fee_rate",
            field=models.DecimalField(
                decimal_places=18,
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="low fee rate",
            ),
        ),
        migrations.AlterField(
            model_name="networkfeerate",
            name="medium_fee_rate",
            field=models.DecimalField(
                decimal_places=18,
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="medium fee rate",
            ),
        ),
        migrations.AlterField(
            model_name="networkfeerate",
            name="mempool_size",
            field=models.BigIntegerField(default=0, verbose_name="mempool size"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=18,
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    ),
                    django.core.validators.MinValueValidator(Decimal("1E-18")),
                ],
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="block_height",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="block height"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin"),
                    ("ethereum", "Ethereum"),
                    ("cardano", "Cardano"),
                    ("polkadot", "Polkadot"),
                ],
                max_length=20,
                verbose_name="blockchain",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="change_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="change address"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="confirmations",
            field=models.IntegerField(default=0, verbose_name="confirmations"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="confirmed at"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="error message"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0E-18"),
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="fee",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_limit",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="gas limit"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=36,
                null=True,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="gas price",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="nonce",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="nonce"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="retry count"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.CharField(max_length=255, verbose_name="destination address"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="transaction hash",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="utxo_inputs",
            field=models.JSONField(blank=True, null=True, verbose_name="UTXO inputs"),
        ),
        migrations.AlterField(
            model_name="transactionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Transaction Created"),
                    ("validated", "Transaction Validated"),
                    ("signed", "Transaction Signed"),
                    ("broadcasted", "Transaction Broadcasted"),
                    ("confirmed", "Transaction Confirmed"),
                    ("failed", "Transaction Failed"),
                    ("cancelled", "Transaction Cancelled"),
                    ("retry", "Transaction Retry"),
                    ("status_updated", "Status Updated"),
                ],
                max_length=20,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="amount",
            field=models.DecimalField(
                decimal_places=18,
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin"),
                    ("ethereum", "Ethereum"),
                    ("cardano", "Cardano"),
                    ("polkadot", "Polkadot"),
                ],
                max_length=20,
                verbose_name="blockchain",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="estimated_confirmation_time",
            field=models.IntegerField(
                verbose_name="estimated confirmation time (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="estimated_fee",
            field=models.DecimalField(
                decimal_places=18,
                max_digits=36,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="estimated fee",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="fee_priority",
            field=models.CharField(
                choices=[
                    ("low", "Low Priority"),
                    ("medium", "Medium Priority"),
                    ("high", "High Priority"),
                ],
                default="medium",
                max_length=10,
                verbose_name="fee priority",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="gas_limit",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="gas limit"
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="gas_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=36,
                null=True,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=18, max_digits=36
                    )
                ],
                verbose_name="gas price",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="used"),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="network_congestion",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                verbose_name="network congestion",
            ),
        ),
        migrations.AlterField(
            model_name="transactionestimate",
            name="sat_per_byte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="satoshis per byte",
            ),
        ),
        migrations.AlterField(
            model_name="transactionlock",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="transactionlock",
            name="locked_by",
            field=models.CharField(max_length=255, verbose_name="locked by"),
        ),
    ]
