# Generated by Django 4.2.7 on 2026-09-02 05:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blockchain",
                    models.CharField(
                        choices=[
                            ("bitcoin", "Bitcoin"),
                            ("ethereum", "Ethereum"),
                            ("cardano", "Cardano"),
                            ("polkadot", "Polkadot"),
                        ],
                        max_length=20,
                        verbose_name="blockchain",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Public blockchain address",
                        max_length=128,
                        verbose_name="address",
                    ),
                ),
                (
                    "encrypted_private_key",
                    models.TextField(
                        help_text="Private key encrypted with Vault transit backend",
                        verbose_name="encrypted private key",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional human-friendly wallet label",
                        max_length=64,
                        verbose_name="label",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet",
                "verbose_name_plural": "wallets",
                "db_table": "wallets",
                "ordering": ["blockchain"],
            },
        ),
        migrations.CreateModel(
            name="WalletBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18,
                        default=Decimal("0"),
                        max_digits=36,
                        verbose_name="balance",
                    ),
                ),
                (
                    "confirmed_balance",
                    models.DecimalField(
                        decimal_places=18,
                        default=Decimal("0"),
                        max_digits=36,
                        verbose_name="confirmed balance",
                    ),
                ),
                (
                    "unconfirmed_balance",
                    models.DecimalField(
                        decimal_places=18,
                        default=Decimal("0"),
                        max_digits=36,
                        verbose_name="unconfirmed balance",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet balance",
                "verbose_name_plural": "wallet balances",
                "db_table": "wallet_balances",
            },
        ),
        migrations.CreateModel(
            name="WalletAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(max_length=128, verbose_name="address")),
                ("is_used", models.BooleanField(default=False, verbose_name="used")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet address",
                "verbose_name_plural": "wallet addresses",
                "db_table": "wallet_addresses",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("send", "Send"), ("receive", "Receive")],
                        max_length=20,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18, max_digits=36, verbose_name="amount"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=36,
                        null=True,
                        verbose_name="fee",
                    ),
                ),
                (
                    "from_address",
                    models.CharField(max_length=128, verbose_name="from address"),
                ),
                (
                    "to_address",
                    models.CharField(max_length=128, verbose_name="to address"),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "block_height",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="block height"
                    ),
                ),
                (
                    "confirmations",
                    models.IntegerField(default=0, verbose_name="confirmations"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet transaction",
                "verbose_name_plural": "wallet transactions",
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "status"],
                        name="wallet_tran_wallet__7ce472_idx",
                    ),
                    models.Index(
                        fields=["transaction_hash"],
                        name="wallet_tran_transac_721809_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="walletaddress",
            constraint=models.UniqueConstraint(
                fields=("wallet", "address"), name="unique_address_per_wallet"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                fields=("user", "blockchain"), name="unique_wallet_per_user_blockchain"
            ),
        ),
    ]
