# Generated by Django 4.2.7 on 2025-10-21 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cardano', 'Cardano'), ('polkadot', 'Polkadot')], max_length=20, unique=True)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet'), ('regtest', 'Regtest'), ('goerli', 'Goerli'), ('westend', 'Westend')], max_length=20)),
                ('rpc_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('current_block_height', models.BigIntegerField(default=0)),
                ('peer_count', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockchain_nodes',
                'ordering': ['blockchain'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cardano', 'Cardano'), ('polkadot', 'Polkadot')], max_length=20)),
                ('transaction_hash', models.CharField(max_length=128, unique=True)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('fee', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('block_height', models.BigIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'blockchain'], name='blockchain__user_id_38812c_idx'), models.Index(fields=['transaction_hash'], name='blockchain__transac_9bd57a_idx'), models.Index(fields=['status'], name='blockchain__status_946598_idx'), models.Index(fields=['created_at'], name='blockchain__created_35199d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockchainAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cardano', 'Cardano'), ('polkadot', 'Polkadot')], max_length=20)),
                ('address', models.CharField(max_length=128)),
                ('encrypted_private_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_addresses',
                'indexes': [models.Index(fields=['user', 'blockchain'], name='blockchain__user_id_59f432_idx'), models.Index(fields=['address'], name='blockchain__address_a4724c_idx')],
                'unique_together': {('user', 'blockchain', 'address')},
            },
        ),
    ]
