# Generated by Django 4.2.7 on 2026-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockchainaddress",
            options={
                "verbose_name": "Blockchain Address",
                "verbose_name_plural": "Blockchain Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="blockchainnode",
            options={
                "ordering": ["blockchain"],
                "verbose_name": "Blockchain Node",
                "verbose_name_plural": "Blockchain Nodes",
            },
        ),
        migrations.AlterModelOptions(
            name="blockchaintransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Blockchain Transaction",
                "verbose_name_plural": "Blockchain Transactions",
            },
        ),
        migrations.AlterField(
            model_name="blockchainaddress",
            name="address",
            field=models.CharField(max_length=128, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="blockchainaddress",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin"),
                    ("ethereum", "Ethereum"),
                    ("cardano", "Cardano"),
                    ("polkadot", "Polkadot"),
                ],
                max_length=20,
                verbose_name="blockchain",
            ),
        ),
        migrations.AlterField(
            model_name="blockchainaddress",
            name="encrypted_private_key",
            field=models.TextField(verbose_name="encrypted private key"),
        ),
        migrations.AlterField(
            model_name="blockchainaddress",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin"),
                    ("ethereum", "Ethereum"),
                    ("cardano", "Cardano"),
                    ("polkadot", "Polkadot"),
                ],
                max_length=20,
                unique=True,
                verbose_name="blockchain",
            ),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="current_block_height",
            field=models.BigIntegerField(
                default=0, verbose_name="current block height"
            ),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="is_synced",
            field=models.BooleanField(default=False, verbose_name="synchronized"),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="network",
            field=models.CharField(
                choices=[
                    ("mainnet", "Mainnet"),
                    ("testnet", "Testnet"),
                    ("regtest", "Regtest"),
                    ("goerli", "Goerli"),
                    ("westend", "Westend"),
                ],
                max_length=20,
                verbose_name="network",
            ),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="peer_count",
            field=models.IntegerField(default=0, verbose_name="peer count"),
        ),
        migrations.AlterField(
            model_name="blockchainnode",
            name="rpc_url",
            field=models.URLField(verbose_name="RPC URL"),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=18, max_digits=30, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="block_hash",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="block hash"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="block_height",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="block height"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin"),
                    ("ethereum", "Ethereum"),
                    ("cardano", "Cardano"),
                    ("polkadot", "Polkadot"),
                ],
                max_length=20,
                verbose_name="blockchain",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="confirmations",
            field=models.IntegerField(default=0, verbose_name="confirmations"),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="confirmed at"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=30,
                null=True,
                verbose_name="fee",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="from_address",
            field=models.CharField(max_length=128, verbose_name="from address"),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="to_address",
            field=models.CharField(max_length=128, verbose_name="to address"),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="transaction_hash",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="transaction hash"
            ),
        ),
    ]
